# Generated by Django 3.0.6 on 2020-05-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200518_0457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Face',
        ),
    ]
