# Generated by Django 3.0.6 on 2020-05-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='print_file',
            field=models.FileField(default=None, upload_to='print_directory/'),
            preserve_default=False,
        ),
    ]
