# Generated by Django 3.0.6 on 2020-05-17 00:43

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_print_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='print_file',
            field=models.FileField(upload_to=feed.models.user_directory_path),
        ),
    ]
